collections:
  - name: ansible.posix
    version: 1.6.2
  - name: community.docker
    version: 4.5.2
  - name: community.general
    version: 10.7.0

roles:
  - name: geerlingguy.docker
    version: 7.4.7
