collections:
  - name: ansible.posix
    version: 2.1.0
  - name: community.docker
    version: 4.8.3
  - name: community.general
    version: 11.4.0

roles:
  - name: geerlingguy.docker
    version: 7.8.0
