collections:
  - name: ansible.posix
    version: 2.1.0
  - name: community.docker
    version: 5.0.5
  - name: community.general
    version: 12.4.0

roles:
  - name: geerlingguy.docker
    version: 8.0.0
