collections:
  - name: ansible.posix
    version: 2.0.0
  - name: community.docker
    version: 4.6.1
  - name: community.general
    version: 10.7.0

roles:
  - name: geerlingguy.docker
    version: 7.4.7
