collections:
  - name: ansible.posix
    version: 2.1.0
  - name: community.docker
    version: 4.8.2
  - name: community.general
    version: 12.0.1

roles:
  - name: geerlingguy.docker
    version: 7.8.0
