- name: Install nftables
  ansible.builtin.apt:
    name: nftables
    state: present

- name: Create nftables rules file
  ansible.builtin.template:
    src: nftables.conf.j2
    dest: /etc/nftables.conf
    mode: "0644"
  notify: Restart nftables
