#!/bin/bash

docker compose \
  -f /etc/plex/docker-compose.yaml \
  -f /etc/plex/arr.docker-compose.yaml \
  -f /etc/plex/plex.docker-compose.yaml \
  -f /etc/plex/edgeshark.docker-compose.yaml \
  "$@"
