unprivileged_user: proxy
ssh:
  user_name: proxy
  host_name: plex-proxy
  public_key_to_add: "change-me"
wireguard:
  port: 51820
  subnet: "10.0.0.1/24"
  private_key: "change-me"
  # plex
  target:
    address: "10.0.0.2"
    public_key: "change-me"
    allowed_ips: "10.0.0.2/24"
    endpoint: "plex-ip"
    port: 51820
    persistent_keepalive: 25
tailscale_auth_key: "[optional] change-me"
nftables:
  whitelisted_ips:
    - "22"
    - "80"
    - "443"
    - "{{ wireguard.port }}"
