# code: language=ansible
- name: Ensure authelia directory exists
  ansible.builtin.file:
    path: /etc/plex/services/authelia
    state: directory
    owner: "{{ unprivileged_user }}"
    mode: "0744"

- name: Deploy authelia configuration
  ansible.builtin.template:
    src: authelia/configuration.yaml.j2
    dest: /etc/plex/services/authelia/configuration.yml
    owner: "{{ unprivileged_user }}"
    mode: "0644"
  notify: "Restart authelia"

- name: Deploy authelia users database
  ansible.builtin.template:
    src: authelia/users_database.yaml.j2
    dest: /etc/plex/services/authelia/users_database.yml
    owner: "{{ unprivileged_user }}"
    mode: "0644"
  notify: "Restart authelia"
