# code: language=ansible
- name: Ensure caddy directory exists
  ansible.builtin.file:
    path: /etc/plex/services/caddy
    state: directory
    owner: "{{ unprivileged_user }}"
    mode: "0744"

- name: Copy caddy proxy script
  ansible.builtin.copy:
    src: caddy-proxy.sh
    dest: /etc/plex/services/caddy/config/caddy-proxy.sh
    owner: "{{ unprivileged_user }}"
    mode: "0744"

- name: Deploy caddy configuration
  ansible.builtin.template:
    src: caddy/Caddyfile.j2
    dest: /etc/plex/services/caddy/config/Caddyfile
    owner: "{{ unprivileged_user }}"
    mode: "0644"
  notify:
    - Restart caddy
